[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "About"
  pageRef = "about"
  weight = 30

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 40

[[footer]]
  name = "Legal Notice"
  pageRef = "impressum"
  weight = 10

[[footer]]
  name = "Privacy Policy"
  pageRef = "datenschutz"
  weight = 20
