services:
  hugo:
    image: hugomods/hugo:exts-0.145.0
    container_name: blanpa-dev
    ports:
      - "1314:1313"
    volumes:
      - .:/src
    command: hugo server --buildDrafts --bind 0.0.0.0
